// No edit this file, this file is generated by generate-icons.js
import { ReactComponent as Arrow } from '../../icons/processed/arrow.svg';
import { ReactComponent as Home } from '../../icons/processed/home.svg';

const iconMap = {
  arrow: Arrow,
  home: Home
};

export const Icon = ({ name, size = 24, color = 'black' }: { name: keyof typeof iconMap; size?: number; color?: string }) => {
  const SvgIcon = iconMap[name];
  return SvgIcon ? <SvgIcon width={size} height={size} fill={color} /> : null;
};

Icon.displayName = 'Icon';
